ContactsManager.UI/Controllers/PersonsController.cs
using ContactsManager.ServiceContracts;
using ContactsManager.ServiceContracts.DTO;
using ContactsManager.ServiceContracts.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Server.IISIntegration;

namespace ContactsManager.UI.Controllers;

[Controller]
[Route("[Controller]")]
public sealed class PersonsController : Controller
{
    private readonly IPersonsService _personsService;
    private readonly ICountriesService _countriesService;
    public PersonsController(IPersonsService personsService,
                             ICountriesService countriesService)
    {
        _personsService = personsService;
        _countriesService = countriesService;
    }
    [Route("/")]
    [Route("[Action]")]
    public IActionResult Index(string searchBy,
                               string searchString,
                               string sortBy = nameof(PersonResponse.PersonName),
                               SortOrderEnum sortOrder = SortOrderEnum.Asc)
    {
        ViewBag.SearchFields = new Dictionary<string, string>()
        {
            { nameof(PersonResponse.PersonName), "Person Name"},
            { nameof(PersonResponse.Email), "Email"},
            { nameof(PersonResponse.DateOfBirth), "Date of Birth"},
            { nameof(PersonResponse.Gender), "Gender"},
            { nameof(PersonResponse.CountryName), "Country"},
            { nameof(PersonResponse.Address), "Address"},
            { nameof(PersonResponse.ReceiveNewsLetters), "Receive news letters"},
            { nameof(PersonResponse.Age), "Age"}

        };

        // filtering persons
        ViewBag.CurrentSearchBy = searchBy;
        ViewBag.CurrentSearchString = searchString;
        List<PersonResponse> persons = _personsService.GetFilteredPersons(searchBy, searchString);

        // sorting persons
        ViewBag.CurrentSortBy = sortBy;
        ViewBag.CurrentSortOrder = sortOrder;
        List<PersonResponse> sortedPersons = _personsService.GetSortedPersons(persons, sortBy, sortOrder);
        return View("Index", sortedPersons);
    }

    [HttpGet("[Action]")]
    public IActionResult SearchTable(string searchBy,
                                     string searchString,
                                     string sortBy = nameof(PersonResponse.PersonName),
                                     SortOrderEnum sortOrder = SortOrderEnum.Asc)
    {
        return ViewComponent("PersonsTable", new
        {
            searchBy,
            searchString,
            sortBy,
            sortOrder
        });
    }


    [HttpGet("[Action]")]
    public IActionResult Create()
    {
        List<CountryResponse> countries = _countriesService.GetAllCountries();
        ViewBag.Countries = countries.Select(country => new SelectListItem() { Text = country.CountryName, Value = country.CountryId });
        return View("Create");
    }

    [HttpPost("[Action]")]
    public IActionResult Create(PersonAddRequest personAddRequest)
    {
        if (!ModelState.IsValid)
        {
            List<CountryResponse> countries = _countriesService.GetAllCountries();
            ViewBag.Countries = countries.Select(country => new SelectListItem() { Text = country.CountryName, Value = country.CountryId });
            ViewBag.Errors = ModelState.Values.SelectMany(e => e.Errors).Select(e => e.ErrorMessage).ToList();
            return View("Create");
        }
        PersonResponse response = _personsService.AddPerson(personAddRequest);
        return RedirectToAction("Index", "Persons");
    }

    [HttpGet("[Action]")]
    public IActionResult Edit(string personId)
    {
        List<CountryResponse> countries = _countriesService.GetAllCountries();
        ViewBag.Countries = countries.Select(country => new SelectListItem() { Text = country.CountryName, Value = country.CountryId });
        PersonResponse? person = _personsService.GetPersonByPersonId(personId);
        PersonUpdateRequest updateRequest = person!.ConvetToPersonUpdateRequest();
        return View("Edit", updateRequest);
    }

    [HttpPost("[Action]")]
    public IActionResult Edit(PersonUpdateRequest personUpdateRequest)
    {
        if (!ModelState.IsValid)
        {
            List<CountryResponse> countries = _countriesService.GetAllCountries();
            ViewBag.Countries = countries.Select(country => new SelectListItem() { Text = country.CountryName, Value = country.CountryId });
            ViewBag.Errors = ModelState.Values.SelectMany(e => e.Errors).Select(e => e.ErrorMessage).ToList();
            return View("Edit");
        }
        PersonResponse? response = _personsService.UpdatePerson(personUpdateRequest);
        return RedirectToAction("Index", "Persons");
    }

    [HttpGet("[Action]")]
    public IActionResult Delete(string personId)
    {
        PersonResponse? person = _personsService.GetPersonByPersonId(personId);
        return View("Delete", person);
    }

    [HttpPost("[Action]")]
    public IActionResult Delete(string personId, string personName)
    {
        bool idDeleted = _personsService.DeletePerson(personId);
        if (idDeleted)
            return RedirectToAction("Index","Persons");
        return RedirectToAction("Delete", "Persons");
    }
}

ContactsManager.UI/ViewComponents/PersonsTableViewComponent.cs
using ContactsManager.ServiceContracts;
using ContactsManager.ServiceContracts.Enums;
using Microsoft.AspNetCore.Mvc;

namespace ContactsManager.UI.ViewComponents;

[ViewComponent]
public sealed class PersonsTableViewComponent:ViewComponent
{
    private readonly IPersonsService _personsService;
    public PersonsTableViewComponent(IPersonsService personsService)
    {
        _personsService = personsService;
    }

    public IViewComponentResult Invoke(string searchBy,
                                       string searchString,
                                       string sortBy,
                                       SortOrderEnum sortOrder)
    {
        var persons = _personsService.GetFilteredPersons(searchBy, searchString);
        var sorted = _personsService.GetSortedPersons(persons, sortBy, sortOrder);
        return View(sorted);
    }
}

ContactsManager.UI/Views/Persons/Create.cshtml
@model PersonAddRequest
@{
    ViewBag.Title = "Create Person";
}
<a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons List</a>

<h2>Create Person</h2>

<div class="w-50">
    <form asp-controller="Persons" asp-action="Create" method="post">

        @*Person Name*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt" asp-for="PersonName">Person Name</label>
            </div>
            <div class="flex-1">
                <input asp-for="PersonName" class="form-input" />
                <span asp-validation-for="PersonName"></span>
            </div>
        </div>

        @*Email*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt" asp-for="Email">Email</label>
            </div>
            <div class="flex-1">
                <input asp-for="Email" type="email" class="form-input" />
                <span asp-validation-for="Email"></span>
            </div>
        </div>

        @*Date of Birth*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt" asp-for="DateOfBirth">Date Of Birth</label>
            </div>
            <div class="flex-1">
                <input asp-for="DateOfBirth" type="date" id="DateOfBirth" name="DateOfBirth" class="form-input" />
                <span asp-validation-for="DateOfBirth"></span>
            </div>
        </div>

        @*Gender*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt">Gender</label>
            </div>
            <div class="flex-1">
                @{
                    string[] genders = (string[])Enum.GetNames(typeof(GenderOptions));
                }
                @foreach (string gender in genders)
                {
                    <input asp-for="Gender" type="radio" value="@gender" />
                    <label for="@gender">@gender</label>

                }
                <span asp-validation-for="Gender"></span>
            </div>
        </div>

        @*Country*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt" asp-for="CountryId">Country</label>
            </div>
            <div class="flex-1">
                <select asp-for="CountryId" asp-items="ViewBag.Countries" class="form-input">
                    <option selected>Please Select</option>
                </select>
                <span asp-validation-for="CountryId"></span>
            </div>
        </div>

        @*Address*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt" asp-for="Address">Address</label>
            </div>
            <div class="flex-1">
                <textarea asp-for="Address" class="form-input"></textarea>
            </div>
            <span asp-validation-for="Address"></span>
        </div>

        @*Receive News Letters*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <input asp-for="ReceiveNewsLetters" value="true" class="form-input" />
                <label asp-for="ReceiveNewsLetters" class="form-label">Receive News Letters</label>
            </div>
            <span asp-validation-for="ReceiveNewsLetters"></span>
        </div>

        <button  class="button button-green-back">Submit</button>
        <div asp-validation-summary="All"></div>

        @if (ViewBag.Errors != null)
        {
            <ul class="text-red">
                @foreach (var error in ViewBag.Errors)
                {
                    <li>@error</li>
                }
            </ul>

        }
    </form>
</div>

@section scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
            asp-fallback-test="window.jQuery"
            asp-fallback-src="~/js/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.21.0/jquery.validate.min.js"
            integrity="sha512-KFHXdr2oObHKI9w4Hv1XPKc898mE4kgYx58oqsc/JqqdLMDI4YjOLzom+EMlW8HFUd0QfjfAvxSL6sEq/a42fQ=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
            asp-fallback-test="window.jQuery.validator"
            asp-fallback-src="~/js/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js"
            integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
            asp-fallback-test="window.jQuery.validator.unobtrusive"
            asp-fallback-src=""></script>

}

ContactsManager.UI/Views/Persons/Delete.cshtml
@model PersonResponse
@{
    ViewBag.Title = "Delete Person";
}
<a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons List</a>

<h2>Delete Person</h2>

<div class="w-50">
    <form asp-controller="Persons" asp-action="Delete" method="post">
        <input type="hidden" asp-for="PersonId"/>
        @*Person Name*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt" asp-for="PersonName">Person Name</label>
            </div>
            <div class="flex-1">
                <input asp-for="PersonName" class="form-input" />
                <span asp-validation-for="PersonName"></span>
            </div>
        </div>
       

        <button class="button button-green-back">Delete</button>
        <div asp-validation-summary="All"></div>
    </form>
</div>

ContactsManager.UI/Views/Persons/Edit.cshtml
@model PersonUpdateRequest
@{
    ViewBag.Title = "Create Person";
}
<a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons List</a>

<h2>Create Person</h2>

<div class="w-50">
    <form asp-controller="Persons" asp-action="Edit" method="post">

        <input type="hidden" asp-for="PersonId"/>

        @*Person Name*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt" asp-for="PersonName">Person Name</label>
            </div>
            <div class="flex-1">
                <input asp-for="PersonName" class="form-input" />
                <span asp-validation-for="PersonName"></span>
            </div>
        </div>

        @*Email*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt" asp-for="Email">Email</label>
            </div>
            <div class="flex-1">
                <input asp-for="Email" type="email" class="form-input" />
                <span asp-validation-for="Email"></span>
            </div>
        </div>

        @*Date of Birth*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt" asp-for="DateOfBirth">Date Of Birth</label>
            </div>
            <div class="flex-1">
                <input asp-for="DateOfBirth" type="date" id="DateOfBirth" name="DateOfBirth" class="form-input" />
                <span asp-validation-for="DateOfBirth"></span>
            </div>
        </div>

        @*Gender*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt">Gender</label>
            </div>
            <div class="flex-1">
                @{
                    string[] genders = (string[])Enum.GetNames(typeof(GenderOptions));
                }
                @foreach (string gender in genders)
                {
                    <input asp-for="Gender" type="radio" value="@gender" />
                    <label for="@gender">@gender</label>

                }
                <span asp-validation-for="Gender"></span>
            </div>
        </div>

        @*Country*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt" asp-for="CountryId">Country</label>
            </div>
            <div class="flex-1">
                <select asp-for="CountryId" asp-items="ViewBag.Countries" class="form-input">
                    <option selected>Please Select</option>
                </select>
                <span asp-validation-for="CountryId"></span>
            </div>
        </div>

        @*Address*@
        <div class="form-field flex">
            <div class="w-25">
                <label class="form-label pt" asp-for="Address">Address</label>
            </div>
            <div class="flex-1">
                <textarea asp-for="Address" class="form-input"></textarea>
            </div>
            <span asp-validation-for="Address"></span>
        </div>

        @*Receive News Letters*@
        <div class="form-field flex">
            <div class="w-25">
            </div>
            <div class="flex-1">
                <input asp-for="ReceiveNewsLetters" value="true" class="form-input" />
                <label asp-for="ReceiveNewsLetters" class="form-label">Receive News Letters</label>
            </div>
            <span asp-validation-for="ReceiveNewsLetters"></span>
        </div>

        <button class="button button-green-back">Submit</button>
        <div asp-validation-summary="All"></div>

        @if (ViewBag.Errors != null)
        {
            <ul class="text-red">
                @foreach (var error in ViewBag.Errors)
                {
                    <li>@error</li>
                }
            </ul>

        }
    </form>
</div>

@section scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
            integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
            asp-fallback-test="window.jQuery"
            asp-fallback-src="~/js/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.21.0/jquery.validate.min.js"
            integrity="sha512-KFHXdr2oObHKI9w4Hv1XPKc898mE4kgYx58oqsc/JqqdLMDI4YjOLzom+EMlW8HFUd0QfjfAvxSL6sEq/a42fQ=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
            asp-fallback-test="window.jQuery.validator"
            asp-fallback-src="~/js/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js"
            integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"
            asp-fallback-test="window.jQuery.validator.unobtrusive"
            asp-fallback-src=""></script>

}

ContactsManager.UI/Views/Persons/Index.cshtml
@model IEnumerable<PersonResponse>
@{
    ViewBag.Title = "Persons";
}

<form id="searchForm">
    <h2>Persons</h2>

    <a asp-controller="Persons" asp-action="Create">Create Person</a>
    <div class="box flex">
        <div class="flex-1">
            <select class="form-input" name="searchBy">
                @foreach (var field in ViewBag.SearchFields)
                {
                    if (field.Key == ViewBag.CurrentSearchBy)
                    {
                        <option selected="selected" value="@field.Key">@field.Value</option>
                    }
                    else
                    {
                        <option value="@field.Key">@field.Value</option>
                    }

                }
            </select>
        </div>

        <div class="flex-1">
            <input value="@ViewBag.CurrentSearchString" type="search" id="Search" class="form-input" placeholder="Search" name="searchString" />
        </div>

        <div class="flex-1">
            <button id="button-search" class="button button-blue-back">Search</button>
            <a asp-controller="Persons" asp-action="Index" class="link-hover">Clear All</a>
        </div>
    </div>

    <table class="table w-100 mt">
        <thead>
            <tr>

                @await Html.PartialAsync("_ColumnHeader", new ViewDataDictionary(ViewData)
                {
                    { "ColumnName", nameof(PersonResponse.PersonName)},
                                { "DisplayName", "Person Name"}
                })
                @await Html.PartialAsync("_ColumnHeader", new ViewDataDictionary(ViewData)
                                {
                    { "ColumnName", nameof(PersonResponse.Email)},
                                { "DisplayName", "Email"}
                })
                @await Html.PartialAsync("_ColumnHeader", new ViewDataDictionary(ViewData)
                                {
                    { "ColumnName", nameof(PersonResponse.DateOfBirth)},
                                { "DisplayName", "Date of Birth"}
                })
                @await Html.PartialAsync("_ColumnHeader", new ViewDataDictionary(ViewData)
                                {
                    { "ColumnName", nameof(PersonResponse.Age)},
                                { "DisplayName", "Age"}
                })
                @await Html.PartialAsync("_ColumnHeader", new ViewDataDictionary(ViewData)
                                {
                    { "ColumnName", nameof(PersonResponse.Gender)},
                                { "DisplayName", "Gender"}
                })
                @await Html.PartialAsync("_ColumnHeader", new ViewDataDictionary(ViewData)
                                {
                    { "ColumnName", nameof(PersonResponse.Address)},
                                { "DisplayName", "Address"}
                })
                @await Html.PartialAsync("_ColumnHeader", new ViewDataDictionary(ViewData)
                                {
                    { "ColumnName", nameof(PersonResponse.CountryName)},
                                { "DisplayName", "Country"}
                })
                @await Html.PartialAsync("_ColumnHeader", new ViewDataDictionary(ViewData)
                                {
                    { "ColumnName", nameof(PersonResponse.ReceiveNewsLetters)},
                                { "DisplayName", "Receive News Letters"}
                })
                <th>Actions</th>
            </tr>
        </thead>

        <tbody id="persons-table-body" class="table-body">
            @await Component.InvokeAsync("PersonsTable", new
                        {
                searchBy = ViewBag.CurrentSearchBy,
                        searchString = ViewBag.CurrentSearchString,
                        sortBy = ViewBag.CurrentSortBy,
                        sortOrder = ViewBag.CurrentSortOrder
                        })


        </tbody>
    </table>
</form>

ContactsManager.UI/Views/Shared/Components/PersonsTable/Default.cshtml
@model IEnumerable<PersonResponse>
@foreach (var person in Model)
{
    <tr>
        <td>@person.PersonName</td>
        <td>@person.Email</td>
        <td>@person.DateOfBirth</td>
        <td>@person.Age</td>
        <td>@person.Gender</td>
        <td>@person.Address</td>
        <td>@person.CountryName</td>
        <td>@person.ReceiveNewsLetters</td>
        <td><a asp-controller="Persons" asp-action="Edit" asp-route-personid="@person.PersonId">Edit</a> | <a asp-controller="Persons" asp-action="Delete" asp-route-personId="@person.PersonId">Delete</a></td>
        
    </tr>
}

ContactsManager.UI/Views/Shared/_ColumnHeader.cshtml
@if (ViewBag.CurrentSortBy == ViewBag.ColumnName && ViewBag.CurrentSortOrder == SortOrderEnum.Asc)
{
    <th><a href="~/persons/index?sortBy=@ViewBag.ColumnName&sortOrder=@SortOrderEnum.Desc&searchBy=@ViewBag.CurrentSearchBy&searchString=@ViewBag.CurrentSearchString">@ViewData["DisplayName"]</a></th>
}
else if (ViewBag.CurrentSortBy == ViewBag.ColumnName && ViewBag.CurrentSortOrder == SortOrderEnum.Desc)
{
    <th><a href="~/persons/index?sortBy=@ViewBag.ColumnName&sortOrder=@SortOrderEnum.Asc&searchBy=@ViewBag.CurrentSearchBy&searchString=@ViewBag.CurrentSearchString">@ViewBag.DisplayName</a></th>
}
else
{
    <th><a href="~/persons/index?sortBy=@ViewBag.ColumnName&sortOrder=@SortOrderEnum.Desc&searchBy=@ViewBag.CurrentSearchBy&searchString=@ViewBag.CurrentSearchString">@ViewBag.DisplayName</a></th>
}

ContactsManager.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css"
          integrity="sha512-xX2rYBFJSj86W54Fyv1de80DWBq7zYLn2z0I9bIhQG+rxIF6XVJUpdGnsNHWRa6AvP89vtFupEPDP8eZAtu9qA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />


</head>
<body>
    <div class="container">
        <div class="navbar">
            <div class="navbar-brand">Contacts Manager</div>
            <ul>
                <li><a asp-controller="Persons" asp-action="Index">Persons</a></li>
            </ul>
        </div>

        <div class="page-content">
            @RenderBody()
        </div>
    </div>
    @RenderSection("scripts", required:false)
    <script src="~/js/Script.js"></script>
</body>
</html>